@BaseUrl = http://localhost:5024
@AuthBaseUrl = http://localhost:5260
@ContentType = application/json

### 1️⃣ ЛОГИН (получить токен)
POST {{AuthBaseUrl}}/api/auth/login
Content-Type: {{ContentType}}

{
  "email": "dodik@gmail.com",
  "passwordHash": "123456"
}


###

### 2️⃣ GET КОРЗИНА
GET {{BaseUrl}}/api/cart
Authorization: Bearer @token

###

### 3️⃣ POST ОБНОВИТЬ
POST {{BaseUrl}}/api/cart
Content-Type: {{ContentType}}
Authorization: Bearer @token

[
  {
    "productId": "550e8400-e29b-41d4-a716-446655440000",
    "quantity": 2
  }
]

###

### 4️⃣ DELETE
DELETE {{BaseUrl}}/api/cart
Authorization: Bearer @token

###